'use client'

import Image from 'next/image'
import { ChevronLeft, Send } from 'lucide-react'
import type { ChatMessage } from './data'

type InternalChatProps = { messages: ChatMessage[]; text: string; onTextChange: (value: string) => void; onSend: (value?: string) => void; onClose: () => void }

export function InternalChat({ messages, text, onTextChange, onSend, onClose }: InternalChatProps) {
  return <div className="fixed inset-0 z-50 bg-background" role="dialog" aria-modal="true" aria-label="المحادثة الداخلية"><div className="safe-top flex h-20 items-center justify-between border-b border-white/10 px-5"><button onClick={onClose} aria-label="العودة" className="icon-button"><ChevronLeft className="size-5" /></button><div className="text-center"><h2 className="text-sm font-bold text-white">مساحتك مع تاون ميديا</h2><p className="mt-1 flex items-center justify-center gap-1.5 text-[11px] text-cyan"><span className="size-1.5 rounded-full bg-cyan" />متصل الآن</p></div><Image src="/town-media-logo.png" alt="تاون ميديا" width={40} height={40} className="size-10 rounded-xl object-cover" /></div><div className="flex h-[calc(100dvh-5rem)] flex-col"><div className="flex-1 overflow-y-auto px-5 py-6"><div className="mx-auto mb-6 max-w-xs rounded-full border border-cyan/15 bg-cyan/5 px-4 py-2 text-center text-[11px] text-cyan/80">محادثة داخلية خاصة بالمشروع</div><div className="mx-auto flex max-w-md flex-col gap-3">{messages.map((message) => <div key={message.id} className={`flex ${message.from === 'user' ? 'justify-start' : 'justify-end'}`}><div className={`max-w-[82%] rounded-[1.35rem] px-4 py-3 ${message.from === 'user' ? 'rounded-br-md bg-white text-navy' : 'rounded-bl-md border border-white/10 bg-card text-white'}`}><p className="text-sm leading-6">{message.text}</p><span className={`mt-1 block text-[10px] ${message.from === 'user' ? 'text-navy/45' : 'text-white/35'}`}>{message.time}</span></div></div>)}</div></div><div className="border-t border-white/10 bg-card/80 px-4 pb-3 pt-3 backdrop-blur-xl"><div className="no-scrollbar mb-3 flex gap-2 overflow-x-auto"><button onClick={() => onSend('أريد اختيار قالب مناسب')} className="quick-reply">اختيار قالب مناسب</button><button onClick={() => onSend('أريد تصميم مخصص')} className="quick-reply">أريد تصميم مخصص</button><button onClick={() => onSend('ما هي الخطوات؟')} className="quick-reply">ما هي الخطوات؟</button></div><form onSubmit={(event) => { event.preventDefault(); onSend() }} className="flex items-end gap-2 rounded-2xl border border-white/10 bg-white/5 p-2"><textarea value={text} onChange={(event) => onTextChange(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey && !event.nativeEvent.isComposing && event.keyCode !== 229) { event.preventDefault(); onSend() } }} rows={1} aria-label="اكتب رسالتك" placeholder="اكتب رسالتك هنا..." className="max-h-24 min-h-10 flex-1 resize-none bg-transparent px-2 py-2 text-sm text-white outline-none placeholder:text-white/35" /><button type="submit" aria-label="إرسال الرسالة" className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-white text-navy"><Send className="size-4" /></button></form></div></div></div>
}
